### ISSUE TITLE
Add option Playlist to a Single MP3 possible ?

### ISSUE THREAD

**Issue by ds2k5** [ebiwoxite/yt-playlist-to-mp3#1]
Hello,
is it possible that you add a Option that a playlist with may 50 Tracks
ends in a single MP3 file so that got one big MP3 file ?!

thanks

**Comment by ebiwoxite** [comment]
Hi,
I added this option in the latest commit.
You can now specify the -s option to do just that :
``` ./yt-playlist-to-mp3.sh -d /home/user/youneedtochangethis -u  https://music.youtube.com/playlist?list=RDCLAK5uy_mFeKbwD6X5axmhNcvd -s ```

**Comment by ds2k5** [comment]
@ebiwoxite 

thank you for your work!

 but did not work with this link for example:  https://www.youtube.com/playlist?list=OLAK5uy_nfberC8nMrqN82G8DJYxWgF6RGUwQoOzc

in Destination Directory find : .ytdl and .part files
but no big MP3 file

**Comment by ebiwoxite** [comment]
I don't have this problem, when I execute the script with your link it works well for me: 

``` ./yt-playlist-to-mp3.sh -d /home/directory -u https://www.youtube.com/playlist\?list\=OLAK5uy_nfberC8nMrqN82G8DJYxWgF6RGUwQoOzc -s ```

Although if you have .part and .ytdl files I think the problem comes from **yt-dlp** so make sure you have the latest version installed.

And if you just wanted this playlist in particular you can find it here: https://we.tl/t-pJEPOqeaoX

**Comment by ds2k5** [comment]
sorry my fault.... had a old yt-dlp in the system...
so I modifyed your .sh from yt-dlp to ./yt-dlp and put newer yt-dlp in destination folder....
now it works!

thank you so much!

**Comment by ebiwoxite** [comment]
You're welcome :)
